name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Run a one-line script
        run: echo Hello, world!
  job_2:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > file.txt
      - uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt
  job_3:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_2
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: file
      - run: cat file.txt
